### ISSUE TITLE
WebPluginPath

### ISSUE THREAD

**Issue by monobogdan** [dliw/fpCEF3#26]
I try use functions from cef3lib but i take SIGSEGV.Here is my code:
CefAddWebPluginPath(ExtractFilePath(Application.ExeName) + 'plugins/');

**Comment by dliw** [comment]
Actually you could have reopened your previous issue, sorry for closing too early.

What you need to set a _directory_ is `CefAddWebPluginDirectory`, see [here](https://github.com/dliw/fpCEF3/blob/master/cef3api.pas#L5289).
`CefAddWebPluginPath` is for __directory + file__.

Make sure this line is only executed __after__ `CefInitialize` is called. I assume you put this line in an initialization section or a TForm.FormCreate - usually cef is __not__ initialized at that point!

That's different from the setting variables like `CefBrowserSubprocessPath`. These _need_ to be set _before_ cef is initialized.

**Comment by monobogdan** [comment]
Thanks!PPAPI is supported? I want PDF, Flash and Unity Web Player31.12.2015, 15:37, "dliw" <notifications@github.com>:Actually you could have reopened your previous issue, sorry for closing too early.

What you need to set a directory is CefAddWebPluginDirectory, see here.
CefAddWebPluginPath is for directory + file.

Make sure this line is only executed after CefInitialize is called. I assume you put this line in an initialization section or a TForm.FormCreate - usually cef is not initialized at that point!

That's different from the setting variables like CefBrowserSubprocessPath. These need to be set before cef is initialized.

**Comment by dliw** [comment]
AFAIK only PPAPI is supported. [See here](https://www.chromium.org/developers/npapi-deprecation).

As long as the plugins work with Chrome / Chromium (CEF 3.2454 is based on Chromium 45), they will also work with CEF.

For Flash you need to correctly set up the _pepperflash_ plugin (should be the case if Chrome / Chromium is installed).
The Unity Web Player probably won't work, see [here](http://twiik.net/articles/google-chrome-just-killed-the-unity-web-player).
For PDF you could use something like [pdf.js](https://mozilla.github.io/pdf.js).

--
I cleaned up your answer, somehow your mail program messes up the messages. (Also [here](https://github.com/dliw/fpCEF3/issues/24#issuecomment-167649345))

Please close this issue, if your problem is solved.
