### ISSUE TITLE
Create form dialog with TChromium in it.

### ISSUE THREAD

**Issue by herux** [dliw/fpCEF3#27]
Hi, I am trying to using fpCEF3 on my little project. I am creating 2 form, 1 for Main, and another as dialog form with TChromium in it. but strange things happen, when I click button on Main form to showing dialog form, its show but main form is recreated.

to make it clear, please download this [file](http://expirebox.com/download/5eb5c6c32da07657895382522696fd71.html) before 48hours

I am using fpc 3.0.0 32bit, lazarus svn, on my windows 8.1 vm

thanks

herux

**Comment by dliw** [comment]
I cannot test on Windows, but I can compile it on Linux.
I see what you want to achieve, but that's not how it works - if it only could be that easy...

You need to initialize CEF before a form is shown. So call CefInitialize in your main program (lpr) or at the very latest in the *Initialization* section of the main form.

This might already be everything you need to do - at least on Windows.
To make it work correctly on Linux, please see the LCLCefClient example (webpanel.pas).
Instead of
`TWebPanel = class(TTabSheet)`
you probably need
`TWebPanel = class(TForm)`

**Comment by herux** [comment]
Yes, you are right. second instance is started. 
I followed your advice, I put CefInitialize on lpr, now my problem solve.

thank you

**Comment by dliw** [comment]
Ok, I will close this issue then. Just reopen if you need further help.
