### ISSUE TITLE
Question: Generic Message Router ?

### ISSUE THREAD

**Issue by zbyna** [dliw/fpCEF3#33]
Is Generic Message Router (https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-generic-message-router)  implemented in fpCEF ?
I may not  be able to find it in sources.
Thank you very much for reply.

**Comment by dliw** [comment]
Short version:
No, there is no equivalent of Generic Message Router in fpCEF.

Long version:
First of all, fpCEF provides *all* of the C API of CEF. So whatever is possible with pure C also is possible with Free Pascal.

There is no reference to the *Generic Message Router* in the C API headers, it only exists in the C++ part and therefore is out of reach of fpCEF.
But to me it looks more like a convenience abstraction layer on top of basic CEF functionality rather than additional base functionality.

So I *think* one could implement an equivalent using the the API fpCEF provides.

**Comment by edwinyzh** [comment]
+1

**Comment by zbyna** [comment]
@dliw 
Thanks for clarification.
 I always forget that there is not possible direct interfacing between fpc and c++ :blush: 
Last time I encountered it was my attempt to use open cv.
