### ISSUE TITLE
Download dialog does not work in Linux

### ISSUE THREAD

**Issue by lucianomartini** [dliw/fpCEF3#41]
The Download dialog does not work in Linux. If you click in a file, for example a .doc file, in Windows a dialog will open using fpcef, but in Linux, nothing happen, and there is no errors. 

There is some way to get this working?

**Comment by dliw** [comment]
There surely is a way, but honestly I don't know. Usually I find all the information needed in the CEF API documentation (see the comments in cef3api.pas) or in the CEF forums.

fpCEF is *not* a browser ready to be used, but basically a header translation of the CEF C API. If it works with C, it will also work with Pascal.

I'm working on fpCEF in my limited free time and only using fpCEF as a viewer for modern HTML (there is no alternative for Pascal yet). This also means, that I don't use any of the more advanced features of CEF.

If you need answers and working examples quickly, you could consider to post a [bounty](http://wiki.lazarus.freepascal.org/Bounties).

**Comment by lucianomartini** [comment]
I know that is not a browser ready to use, but in Windows the dialog open... So, i was thinking if that is a issue, very sorry again.

I promises i will never do this anymore.

**Comment by lucianomartini** [comment]
I was wrong. New versions of FPCEF is not working, old versions works. 

I will check it better, but i know that the download is working in the old versions, because old compilations are able to download files...

**Comment by lucianomartini** [comment]
See this topic by me: 
http://forum.lazarus.freepascal.org/index.php?topic=31356.0 

It looks like not working anymore.

**Comment by lucianomartini** [comment]
I am a big idiot, i need to double click the event onbeforedownload and put this code:
http://forum.lazarus.freepascal.org/index.php?topic=31356.0

Sorry very very much .

**Comment by dliw** [comment]
>Sorry very very much .
Actually I'm sorry, as I apparently misunderstood your question. Now I know what you meant with "download dialog".

I'm glad you could solve your issue and it also works on Linux.

Btw:
Don't hesitate to ask questions, but try to be as specific as possible or show the relevant code snippets, otherwise it takes me lot of time to understand and reproduce an issue.

If you need help or have specific questions regarding implementation, it is better to ask in the lazarus forums or write me a mail directly (dev.dliw@gmail.com).
If you don't get an answer in the forums, you can also send me a mail pointing to the forum entry - I'm **not** watching the forum!

And finally: I would like to remove all the off-topic talk from the issue pages, as these are not relevant for others - if you are ok with this.

**Comment by lucianomartini** [comment]
Hi, thank you, i discovered that this command correct the problem in Windows, but still not in Linux!

**Comment by dliw** [comment]
The problem is this:

```
WARNING:file_dialog_manager.cc(332)] No file dialog runner available for this platform
```

This means one needs to implement a file dialog handler. A reference implementation can be found at https://bitbucket.org/chromiumembedded/cef/src/9928036f638f3a2e1bcccf18c28d940e473f82cb/tests/cefclient/browser/dialog_handler_gtk.cc

In fpCEF this means implementing the **OnFileDialog** callback.

**Comment by lucianomartini** [comment]
I think when you put the example of printer implementation for Linux, this implementation will be more easy for me!
