### ISSUE TITLE
The latest version for working in windows XP

### ISSUE THREAD

**Issue by AleksandrJS** [dliw/fpCEF3#58]
Hi,

The latest version of Chromium for winXP = 49
Chromium 49 already supports CSS variables.
Http://caniuse.com/#search=css-variables

V3.2526 is Chromium 47 - CSS variables are not supported
V3.2704 is Chromium 51 - does not work in WinXP

My problem is very small and personal,
but I would like to write a single CSS + JavaScript for working in Lazarus + Chromium applications compiled for different OS (winXP and later).

As I understand it, I may have to choose:
- or refuse to use CSS-variables
- or refuse to support WinXP

Regards

**Comment by dliw** [comment]
Actually you have one more option: using [CEF 3.2623](https://bitbucket.org/chromiumembedded/cef/branch/2623) which is based on Chromium 49 and is the last version to support Win XP.

I skipped this version back then and updated directly to CEF 3.2704, because starting with 3.2704 the official builds didn't have tcmalloc enabled, which made things **a lot** easier for me.

The third option for you, is to start from [this revision](https://github.com/dliw/fpCEF3/commit/36679d94f60112366180e9418083ecb9198ea299) and make the necessary changes to fpCEF for CEF 3.2623. AFAIR there were only little changes.
Of course you loose all the bug fixes I made in later revisions.

But you must know for yourself whether such effort is worthwhile for an unsupported operating system.

**Comment by AleksandrJS** [comment]
Thank you.

My qualifications and lack of time do not allow me to work with the resources you indicated.

I would like to be able to quickly add a component (cef3.lpk) to the project (released source code "fpCEF3-3.2623"),
If there is no such possibility, my question can be considered closed.

Best Regards.

**Comment by dliw** [comment]
>I would like to be able to quickly add a component (cef3.lpk) to the project (released source code "fpCEF3-3.2623")

As much as I would like to provide such version of fpCEF, this is not possible right now. Please keep in mind, that I'm working on fpCEF in my free time and lately I'm not even being able to keep up with CEF due to lack of time.

**Comment by AleksandrJS** [comment]
My small problems are not a catastrophe or a grief :)

Thank you for your work!
What you are doing is worthy of great recognition and respect!

I, too, in my free time, try to promote Lazarus + fpCEF3
> www .vcorp.ru/cef3_lazarus/#p2
> ... /cef3_lazarus/options/
> ... /cef3_lazarus/events/

**Comment by dliw** [comment]
The thing is: you are not the only one to ask for Win XP support and if I had realized that earlier, I wouldn't have skipped this very version. On the other hand, I'm myself only using Linux, so my motivation to put effort into old Windows versions is not too high.

>I, too, in my free time, try to promote Lazarus + fpCEF3

Thumbs up! I know this website and I visit it from time to time to see, if there are any changes.
